#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MediaAndroidTest.Resource", IsApplication=true)]

namespace MediaAndroidTest
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Plugin.Media.Resource.Attribute.font = global::MediaAndroidTest.Resource.Attribute.font;
			global::Plugin.Media.Resource.Attribute.fontProviderAuthority = global::MediaAndroidTest.Resource.Attribute.fontProviderAuthority;
			global::Plugin.Media.Resource.Attribute.fontProviderCerts = global::MediaAndroidTest.Resource.Attribute.fontProviderCerts;
			global::Plugin.Media.Resource.Attribute.fontProviderFetchStrategy = global::MediaAndroidTest.Resource.Attribute.fontProviderFetchStrategy;
			global::Plugin.Media.Resource.Attribute.fontProviderFetchTimeout = global::MediaAndroidTest.Resource.Attribute.fontProviderFetchTimeout;
			global::Plugin.Media.Resource.Attribute.fontProviderPackage = global::MediaAndroidTest.Resource.Attribute.fontProviderPackage;
			global::Plugin.Media.Resource.Attribute.fontProviderQuery = global::MediaAndroidTest.Resource.Attribute.fontProviderQuery;
			global::Plugin.Media.Resource.Attribute.fontStyle = global::MediaAndroidTest.Resource.Attribute.fontStyle;
			global::Plugin.Media.Resource.Attribute.fontWeight = global::MediaAndroidTest.Resource.Attribute.fontWeight;
			global::Plugin.Media.Resource.Boolean.abc_action_bar_embed_tabs = global::MediaAndroidTest.Resource.Boolean.abc_action_bar_embed_tabs;
			global::Plugin.Media.Resource.Color.notification_action_color_filter = global::MediaAndroidTest.Resource.Color.notification_action_color_filter;
			global::Plugin.Media.Resource.Color.notification_icon_bg_color = global::MediaAndroidTest.Resource.Color.notification_icon_bg_color;
			global::Plugin.Media.Resource.Color.ripple_material_light = global::MediaAndroidTest.Resource.Color.ripple_material_light;
			global::Plugin.Media.Resource.Color.secondary_text_default_material_light = global::MediaAndroidTest.Resource.Color.secondary_text_default_material_light;
			global::Plugin.Media.Resource.Dimension.compat_button_inset_horizontal_material = global::MediaAndroidTest.Resource.Dimension.compat_button_inset_horizontal_material;
			global::Plugin.Media.Resource.Dimension.compat_button_inset_vertical_material = global::MediaAndroidTest.Resource.Dimension.compat_button_inset_vertical_material;
			global::Plugin.Media.Resource.Dimension.compat_button_padding_horizontal_material = global::MediaAndroidTest.Resource.Dimension.compat_button_padding_horizontal_material;
			global::Plugin.Media.Resource.Dimension.compat_button_padding_vertical_material = global::MediaAndroidTest.Resource.Dimension.compat_button_padding_vertical_material;
			global::Plugin.Media.Resource.Dimension.compat_control_corner_material = global::MediaAndroidTest.Resource.Dimension.compat_control_corner_material;
			global::Plugin.Media.Resource.Dimension.notification_action_icon_size = global::MediaAndroidTest.Resource.Dimension.notification_action_icon_size;
			global::Plugin.Media.Resource.Dimension.notification_action_text_size = global::MediaAndroidTest.Resource.Dimension.notification_action_text_size;
			global::Plugin.Media.Resource.Dimension.notification_big_circle_margin = global::MediaAndroidTest.Resource.Dimension.notification_big_circle_margin;
			global::Plugin.Media.Resource.Dimension.notification_content_margin_start = global::MediaAndroidTest.Resource.Dimension.notification_content_margin_start;
			global::Plugin.Media.Resource.Dimension.notification_large_icon_height = global::MediaAndroidTest.Resource.Dimension.notification_large_icon_height;
			global::Plugin.Media.Resource.Dimension.notification_large_icon_width = global::MediaAndroidTest.Resource.Dimension.notification_large_icon_width;
			global::Plugin.Media.Resource.Dimension.notification_main_column_padding_top = global::MediaAndroidTest.Resource.Dimension.notification_main_column_padding_top;
			global::Plugin.Media.Resource.Dimension.notification_media_narrow_margin = global::MediaAndroidTest.Resource.Dimension.notification_media_narrow_margin;
			global::Plugin.Media.Resource.Dimension.notification_right_icon_size = global::MediaAndroidTest.Resource.Dimension.notification_right_icon_size;
			global::Plugin.Media.Resource.Dimension.notification_right_side_padding_top = global::MediaAndroidTest.Resource.Dimension.notification_right_side_padding_top;
			global::Plugin.Media.Resource.Dimension.notification_small_icon_background_padding = global::MediaAndroidTest.Resource.Dimension.notification_small_icon_background_padding;
			global::Plugin.Media.Resource.Dimension.notification_small_icon_size_as_large = global::MediaAndroidTest.Resource.Dimension.notification_small_icon_size_as_large;
			global::Plugin.Media.Resource.Dimension.notification_subtext_size = global::MediaAndroidTest.Resource.Dimension.notification_subtext_size;
			global::Plugin.Media.Resource.Dimension.notification_top_pad = global::MediaAndroidTest.Resource.Dimension.notification_top_pad;
			global::Plugin.Media.Resource.Dimension.notification_top_pad_large_text = global::MediaAndroidTest.Resource.Dimension.notification_top_pad_large_text;
			global::Plugin.Media.Resource.Drawable.notification_action_background = global::MediaAndroidTest.Resource.Drawable.notification_action_background;
			global::Plugin.Media.Resource.Drawable.notification_bg = global::MediaAndroidTest.Resource.Drawable.notification_bg;
			global::Plugin.Media.Resource.Drawable.notification_bg_low = global::MediaAndroidTest.Resource.Drawable.notification_bg_low;
			global::Plugin.Media.Resource.Drawable.notification_bg_low_normal = global::MediaAndroidTest.Resource.Drawable.notification_bg_low_normal;
			global::Plugin.Media.Resource.Drawable.notification_bg_low_pressed = global::MediaAndroidTest.Resource.Drawable.notification_bg_low_pressed;
			global::Plugin.Media.Resource.Drawable.notification_bg_normal = global::MediaAndroidTest.Resource.Drawable.notification_bg_normal;
			global::Plugin.Media.Resource.Drawable.notification_bg_normal_pressed = global::MediaAndroidTest.Resource.Drawable.notification_bg_normal_pressed;
			global::Plugin.Media.Resource.Drawable.notification_icon_background = global::MediaAndroidTest.Resource.Drawable.notification_icon_background;
			global::Plugin.Media.Resource.Drawable.notification_template_icon_bg = global::MediaAndroidTest.Resource.Drawable.notification_template_icon_bg;
			global::Plugin.Media.Resource.Drawable.notification_template_icon_low_bg = global::MediaAndroidTest.Resource.Drawable.notification_template_icon_low_bg;
			global::Plugin.Media.Resource.Drawable.notification_tile_bg = global::MediaAndroidTest.Resource.Drawable.notification_tile_bg;
			global::Plugin.Media.Resource.Drawable.notify_panel_notification_icon_bg = global::MediaAndroidTest.Resource.Drawable.notify_panel_notification_icon_bg;
			global::Plugin.Media.Resource.Id.actions = global::MediaAndroidTest.Resource.Id.actions;
			global::Plugin.Media.Resource.Id.action_container = global::MediaAndroidTest.Resource.Id.action_container;
			global::Plugin.Media.Resource.Id.action_divider = global::MediaAndroidTest.Resource.Id.action_divider;
			global::Plugin.Media.Resource.Id.action_image = global::MediaAndroidTest.Resource.Id.action_image;
			global::Plugin.Media.Resource.Id.action_text = global::MediaAndroidTest.Resource.Id.action_text;
			global::Plugin.Media.Resource.Id.async = global::MediaAndroidTest.Resource.Id.async;
			global::Plugin.Media.Resource.Id.blocking = global::MediaAndroidTest.Resource.Id.blocking;
			global::Plugin.Media.Resource.Id.chronometer = global::MediaAndroidTest.Resource.Id.chronometer;
			global::Plugin.Media.Resource.Id.forever = global::MediaAndroidTest.Resource.Id.forever;
			global::Plugin.Media.Resource.Id.icon = global::MediaAndroidTest.Resource.Id.icon;
			global::Plugin.Media.Resource.Id.icon_group = global::MediaAndroidTest.Resource.Id.icon_group;
			global::Plugin.Media.Resource.Id.info = global::MediaAndroidTest.Resource.Id.info;
			global::Plugin.Media.Resource.Id.italic = global::MediaAndroidTest.Resource.Id.italic;
			global::Plugin.Media.Resource.Id.line1 = global::MediaAndroidTest.Resource.Id.line1;
			global::Plugin.Media.Resource.Id.line3 = global::MediaAndroidTest.Resource.Id.line3;
			global::Plugin.Media.Resource.Id.normal = global::MediaAndroidTest.Resource.Id.normal;
			global::Plugin.Media.Resource.Id.notification_background = global::MediaAndroidTest.Resource.Id.notification_background;
			global::Plugin.Media.Resource.Id.notification_main_column = global::MediaAndroidTest.Resource.Id.notification_main_column;
			global::Plugin.Media.Resource.Id.notification_main_column_container = global::MediaAndroidTest.Resource.Id.notification_main_column_container;
			global::Plugin.Media.Resource.Id.right_icon = global::MediaAndroidTest.Resource.Id.right_icon;
			global::Plugin.Media.Resource.Id.right_side = global::MediaAndroidTest.Resource.Id.right_side;
			global::Plugin.Media.Resource.Id.tag_transition_group = global::MediaAndroidTest.Resource.Id.tag_transition_group;
			global::Plugin.Media.Resource.Id.text = global::MediaAndroidTest.Resource.Id.text;
			global::Plugin.Media.Resource.Id.text2 = global::MediaAndroidTest.Resource.Id.text2;
			global::Plugin.Media.Resource.Id.time = global::MediaAndroidTest.Resource.Id.time;
			global::Plugin.Media.Resource.Id.title = global::MediaAndroidTest.Resource.Id.title;
			global::Plugin.Media.Resource.Integer.status_bar_notification_info_maxnum = global::MediaAndroidTest.Resource.Integer.status_bar_notification_info_maxnum;
			global::Plugin.Media.Resource.Layout.notification_action = global::MediaAndroidTest.Resource.Layout.notification_action;
			global::Plugin.Media.Resource.Layout.notification_action_tombstone = global::MediaAndroidTest.Resource.Layout.notification_action_tombstone;
			global::Plugin.Media.Resource.Layout.notification_template_custom_big = global::MediaAndroidTest.Resource.Layout.notification_template_custom_big;
			global::Plugin.Media.Resource.Layout.notification_template_icon_group = global::MediaAndroidTest.Resource.Layout.notification_template_icon_group;
			global::Plugin.Media.Resource.Layout.notification_template_part_chronometer = global::MediaAndroidTest.Resource.Layout.notification_template_part_chronometer;
			global::Plugin.Media.Resource.Layout.notification_template_part_time = global::MediaAndroidTest.Resource.Layout.notification_template_part_time;
			global::Plugin.Media.Resource.String.status_bar_notification_info_overflow = global::MediaAndroidTest.Resource.String.status_bar_notification_info_overflow;
			global::Plugin.Media.Resource.Style.TextAppearance_Compat_Notification = global::MediaAndroidTest.Resource.Style.TextAppearance_Compat_Notification;
			global::Plugin.Media.Resource.Style.TextAppearance_Compat_Notification_Info = global::MediaAndroidTest.Resource.Style.TextAppearance_Compat_Notification_Info;
			global::Plugin.Media.Resource.Style.TextAppearance_Compat_Notification_Line2 = global::MediaAndroidTest.Resource.Style.TextAppearance_Compat_Notification_Line2;
			global::Plugin.Media.Resource.Style.TextAppearance_Compat_Notification_Time = global::MediaAndroidTest.Resource.Style.TextAppearance_Compat_Notification_Time;
			global::Plugin.Media.Resource.Style.TextAppearance_Compat_Notification_Title = global::MediaAndroidTest.Resource.Style.TextAppearance_Compat_Notification_Title;
			global::Plugin.Media.Resource.Style.Widget_Compat_NotificationActionContainer = global::MediaAndroidTest.Resource.Style.Widget_Compat_NotificationActionContainer;
			global::Plugin.Media.Resource.Style.Widget_Compat_NotificationActionText = global::MediaAndroidTest.Resource.Style.Widget_Compat_NotificationActionText;
			global::Plugin.Media.Resource.Styleable.FontFamily = global::MediaAndroidTest.Resource.Styleable.FontFamily;
			global::Plugin.Media.Resource.Styleable.FontFamilyFont = global::MediaAndroidTest.Resource.Styleable.FontFamilyFont;
			global::Plugin.Media.Resource.Styleable.FontFamilyFont_android_font = global::MediaAndroidTest.Resource.Styleable.FontFamilyFont_android_font;
			global::Plugin.Media.Resource.Styleable.FontFamilyFont_android_fontStyle = global::MediaAndroidTest.Resource.Styleable.FontFamilyFont_android_fontStyle;
			global::Plugin.Media.Resource.Styleable.FontFamilyFont_android_fontWeight = global::MediaAndroidTest.Resource.Styleable.FontFamilyFont_android_fontWeight;
			global::Plugin.Media.Resource.Styleable.FontFamilyFont_font = global::MediaAndroidTest.Resource.Styleable.FontFamilyFont_font;
			global::Plugin.Media.Resource.Styleable.FontFamilyFont_fontStyle = global::MediaAndroidTest.Resource.Styleable.FontFamilyFont_fontStyle;
			global::Plugin.Media.Resource.Styleable.FontFamilyFont_fontWeight = global::MediaAndroidTest.Resource.Styleable.FontFamilyFont_fontWeight;
			global::Plugin.Media.Resource.Styleable.FontFamily_fontProviderAuthority = global::MediaAndroidTest.Resource.Styleable.FontFamily_fontProviderAuthority;
			global::Plugin.Media.Resource.Styleable.FontFamily_fontProviderCerts = global::MediaAndroidTest.Resource.Styleable.FontFamily_fontProviderCerts;
			global::Plugin.Media.Resource.Styleable.FontFamily_fontProviderFetchStrategy = global::MediaAndroidTest.Resource.Styleable.FontFamily_fontProviderFetchStrategy;
			global::Plugin.Media.Resource.Styleable.FontFamily_fontProviderFetchTimeout = global::MediaAndroidTest.Resource.Styleable.FontFamily_fontProviderFetchTimeout;
			global::Plugin.Media.Resource.Styleable.FontFamily_fontProviderPackage = global::MediaAndroidTest.Resource.Styleable.FontFamily_fontProviderPackage;
			global::Plugin.Media.Resource.Styleable.FontFamily_fontProviderQuery = global::MediaAndroidTest.Resource.Styleable.FontFamily_fontProviderQuery;
			global::Plugin.Media.Resource.Xml.xamarin_essentials_fileprovider_file_paths = global::MediaAndroidTest.Resource.Xml.xamarin_essentials_fileprovider_file_paths;
			global::Xamarin.Essentials.Resource.Attribute.font = global::MediaAndroidTest.Resource.Attribute.font;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderAuthority = global::MediaAndroidTest.Resource.Attribute.fontProviderAuthority;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderCerts = global::MediaAndroidTest.Resource.Attribute.fontProviderCerts;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderFetchStrategy = global::MediaAndroidTest.Resource.Attribute.fontProviderFetchStrategy;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderFetchTimeout = global::MediaAndroidTest.Resource.Attribute.fontProviderFetchTimeout;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderPackage = global::MediaAndroidTest.Resource.Attribute.fontProviderPackage;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderQuery = global::MediaAndroidTest.Resource.Attribute.fontProviderQuery;
			global::Xamarin.Essentials.Resource.Attribute.fontStyle = global::MediaAndroidTest.Resource.Attribute.fontStyle;
			global::Xamarin.Essentials.Resource.Attribute.fontWeight = global::MediaAndroidTest.Resource.Attribute.fontWeight;
			global::Xamarin.Essentials.Resource.Boolean.abc_action_bar_embed_tabs = global::MediaAndroidTest.Resource.Boolean.abc_action_bar_embed_tabs;
			global::Xamarin.Essentials.Resource.Color.notification_action_color_filter = global::MediaAndroidTest.Resource.Color.notification_action_color_filter;
			global::Xamarin.Essentials.Resource.Color.notification_icon_bg_color = global::MediaAndroidTest.Resource.Color.notification_icon_bg_color;
			global::Xamarin.Essentials.Resource.Color.ripple_material_light = global::MediaAndroidTest.Resource.Color.ripple_material_light;
			global::Xamarin.Essentials.Resource.Color.secondary_text_default_material_light = global::MediaAndroidTest.Resource.Color.secondary_text_default_material_light;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_inset_horizontal_material = global::MediaAndroidTest.Resource.Dimension.compat_button_inset_horizontal_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_inset_vertical_material = global::MediaAndroidTest.Resource.Dimension.compat_button_inset_vertical_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_padding_horizontal_material = global::MediaAndroidTest.Resource.Dimension.compat_button_padding_horizontal_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_padding_vertical_material = global::MediaAndroidTest.Resource.Dimension.compat_button_padding_vertical_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_control_corner_material = global::MediaAndroidTest.Resource.Dimension.compat_control_corner_material;
			global::Xamarin.Essentials.Resource.Dimension.notification_action_icon_size = global::MediaAndroidTest.Resource.Dimension.notification_action_icon_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_action_text_size = global::MediaAndroidTest.Resource.Dimension.notification_action_text_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_big_circle_margin = global::MediaAndroidTest.Resource.Dimension.notification_big_circle_margin;
			global::Xamarin.Essentials.Resource.Dimension.notification_content_margin_start = global::MediaAndroidTest.Resource.Dimension.notification_content_margin_start;
			global::Xamarin.Essentials.Resource.Dimension.notification_large_icon_height = global::MediaAndroidTest.Resource.Dimension.notification_large_icon_height;
			global::Xamarin.Essentials.Resource.Dimension.notification_large_icon_width = global::MediaAndroidTest.Resource.Dimension.notification_large_icon_width;
			global::Xamarin.Essentials.Resource.Dimension.notification_main_column_padding_top = global::MediaAndroidTest.Resource.Dimension.notification_main_column_padding_top;
			global::Xamarin.Essentials.Resource.Dimension.notification_media_narrow_margin = global::MediaAndroidTest.Resource.Dimension.notification_media_narrow_margin;
			global::Xamarin.Essentials.Resource.Dimension.notification_right_icon_size = global::MediaAndroidTest.Resource.Dimension.notification_right_icon_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_right_side_padding_top = global::MediaAndroidTest.Resource.Dimension.notification_right_side_padding_top;
			global::Xamarin.Essentials.Resource.Dimension.notification_small_icon_background_padding = global::MediaAndroidTest.Resource.Dimension.notification_small_icon_background_padding;
			global::Xamarin.Essentials.Resource.Dimension.notification_small_icon_size_as_large = global::MediaAndroidTest.Resource.Dimension.notification_small_icon_size_as_large;
			global::Xamarin.Essentials.Resource.Dimension.notification_subtext_size = global::MediaAndroidTest.Resource.Dimension.notification_subtext_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_top_pad = global::MediaAndroidTest.Resource.Dimension.notification_top_pad;
			global::Xamarin.Essentials.Resource.Dimension.notification_top_pad_large_text = global::MediaAndroidTest.Resource.Dimension.notification_top_pad_large_text;
			global::Xamarin.Essentials.Resource.Drawable.notification_action_background = global::MediaAndroidTest.Resource.Drawable.notification_action_background;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg = global::MediaAndroidTest.Resource.Drawable.notification_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low = global::MediaAndroidTest.Resource.Drawable.notification_bg_low;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low_normal = global::MediaAndroidTest.Resource.Drawable.notification_bg_low_normal;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low_pressed = global::MediaAndroidTest.Resource.Drawable.notification_bg_low_pressed;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_normal = global::MediaAndroidTest.Resource.Drawable.notification_bg_normal;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_normal_pressed = global::MediaAndroidTest.Resource.Drawable.notification_bg_normal_pressed;
			global::Xamarin.Essentials.Resource.Drawable.notification_icon_background = global::MediaAndroidTest.Resource.Drawable.notification_icon_background;
			global::Xamarin.Essentials.Resource.Drawable.notification_template_icon_bg = global::MediaAndroidTest.Resource.Drawable.notification_template_icon_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_template_icon_low_bg = global::MediaAndroidTest.Resource.Drawable.notification_template_icon_low_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_tile_bg = global::MediaAndroidTest.Resource.Drawable.notification_tile_bg;
			global::Xamarin.Essentials.Resource.Drawable.notify_panel_notification_icon_bg = global::MediaAndroidTest.Resource.Drawable.notify_panel_notification_icon_bg;
			global::Xamarin.Essentials.Resource.Id.actions = global::MediaAndroidTest.Resource.Id.actions;
			global::Xamarin.Essentials.Resource.Id.action_container = global::MediaAndroidTest.Resource.Id.action_container;
			global::Xamarin.Essentials.Resource.Id.action_divider = global::MediaAndroidTest.Resource.Id.action_divider;
			global::Xamarin.Essentials.Resource.Id.action_image = global::MediaAndroidTest.Resource.Id.action_image;
			global::Xamarin.Essentials.Resource.Id.action_text = global::MediaAndroidTest.Resource.Id.action_text;
			global::Xamarin.Essentials.Resource.Id.async = global::MediaAndroidTest.Resource.Id.async;
			global::Xamarin.Essentials.Resource.Id.blocking = global::MediaAndroidTest.Resource.Id.blocking;
			global::Xamarin.Essentials.Resource.Id.chronometer = global::MediaAndroidTest.Resource.Id.chronometer;
			global::Xamarin.Essentials.Resource.Id.forever = global::MediaAndroidTest.Resource.Id.forever;
			global::Xamarin.Essentials.Resource.Id.icon = global::MediaAndroidTest.Resource.Id.icon;
			global::Xamarin.Essentials.Resource.Id.icon_group = global::MediaAndroidTest.Resource.Id.icon_group;
			global::Xamarin.Essentials.Resource.Id.info = global::MediaAndroidTest.Resource.Id.info;
			global::Xamarin.Essentials.Resource.Id.italic = global::MediaAndroidTest.Resource.Id.italic;
			global::Xamarin.Essentials.Resource.Id.line1 = global::MediaAndroidTest.Resource.Id.line1;
			global::Xamarin.Essentials.Resource.Id.line3 = global::MediaAndroidTest.Resource.Id.line3;
			global::Xamarin.Essentials.Resource.Id.normal = global::MediaAndroidTest.Resource.Id.normal;
			global::Xamarin.Essentials.Resource.Id.notification_background = global::MediaAndroidTest.Resource.Id.notification_background;
			global::Xamarin.Essentials.Resource.Id.notification_main_column = global::MediaAndroidTest.Resource.Id.notification_main_column;
			global::Xamarin.Essentials.Resource.Id.notification_main_column_container = global::MediaAndroidTest.Resource.Id.notification_main_column_container;
			global::Xamarin.Essentials.Resource.Id.right_icon = global::MediaAndroidTest.Resource.Id.right_icon;
			global::Xamarin.Essentials.Resource.Id.right_side = global::MediaAndroidTest.Resource.Id.right_side;
			global::Xamarin.Essentials.Resource.Id.tag_transition_group = global::MediaAndroidTest.Resource.Id.tag_transition_group;
			global::Xamarin.Essentials.Resource.Id.text = global::MediaAndroidTest.Resource.Id.text;
			global::Xamarin.Essentials.Resource.Id.text2 = global::MediaAndroidTest.Resource.Id.text2;
			global::Xamarin.Essentials.Resource.Id.time = global::MediaAndroidTest.Resource.Id.time;
			global::Xamarin.Essentials.Resource.Id.title = global::MediaAndroidTest.Resource.Id.title;
			global::Xamarin.Essentials.Resource.Integer.status_bar_notification_info_maxnum = global::MediaAndroidTest.Resource.Integer.status_bar_notification_info_maxnum;
			global::Xamarin.Essentials.Resource.Layout.notification_action = global::MediaAndroidTest.Resource.Layout.notification_action;
			global::Xamarin.Essentials.Resource.Layout.notification_action_tombstone = global::MediaAndroidTest.Resource.Layout.notification_action_tombstone;
			global::Xamarin.Essentials.Resource.Layout.notification_template_custom_big = global::MediaAndroidTest.Resource.Layout.notification_template_custom_big;
			global::Xamarin.Essentials.Resource.Layout.notification_template_icon_group = global::MediaAndroidTest.Resource.Layout.notification_template_icon_group;
			global::Xamarin.Essentials.Resource.Layout.notification_template_part_chronometer = global::MediaAndroidTest.Resource.Layout.notification_template_part_chronometer;
			global::Xamarin.Essentials.Resource.Layout.notification_template_part_time = global::MediaAndroidTest.Resource.Layout.notification_template_part_time;
			global::Xamarin.Essentials.Resource.String.status_bar_notification_info_overflow = global::MediaAndroidTest.Resource.String.status_bar_notification_info_overflow;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification = global::MediaAndroidTest.Resource.Style.TextAppearance_Compat_Notification;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Info = global::MediaAndroidTest.Resource.Style.TextAppearance_Compat_Notification_Info;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Line2 = global::MediaAndroidTest.Resource.Style.TextAppearance_Compat_Notification_Line2;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Time = global::MediaAndroidTest.Resource.Style.TextAppearance_Compat_Notification_Time;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Title = global::MediaAndroidTest.Resource.Style.TextAppearance_Compat_Notification_Title;
			global::Xamarin.Essentials.Resource.Style.Widget_Compat_NotificationActionContainer = global::MediaAndroidTest.Resource.Style.Widget_Compat_NotificationActionContainer;
			global::Xamarin.Essentials.Resource.Style.Widget_Compat_NotificationActionText = global::MediaAndroidTest.Resource.Style.Widget_Compat_NotificationActionText;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily = global::MediaAndroidTest.Resource.Styleable.FontFamily;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont = global::MediaAndroidTest.Resource.Styleable.FontFamilyFont;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_font = global::MediaAndroidTest.Resource.Styleable.FontFamilyFont_android_font;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_fontStyle = global::MediaAndroidTest.Resource.Styleable.FontFamilyFont_android_fontStyle;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_fontWeight = global::MediaAndroidTest.Resource.Styleable.FontFamilyFont_android_fontWeight;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_font = global::MediaAndroidTest.Resource.Styleable.FontFamilyFont_font;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_fontStyle = global::MediaAndroidTest.Resource.Styleable.FontFamilyFont_fontStyle;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_fontWeight = global::MediaAndroidTest.Resource.Styleable.FontFamilyFont_fontWeight;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderAuthority = global::MediaAndroidTest.Resource.Styleable.FontFamily_fontProviderAuthority;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderCerts = global::MediaAndroidTest.Resource.Styleable.FontFamily_fontProviderCerts;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderFetchStrategy = global::MediaAndroidTest.Resource.Styleable.FontFamily_fontProviderFetchStrategy;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderFetchTimeout = global::MediaAndroidTest.Resource.Styleable.FontFamily_fontProviderFetchTimeout;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderPackage = global::MediaAndroidTest.Resource.Styleable.FontFamily_fontProviderPackage;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderQuery = global::MediaAndroidTest.Resource.Styleable.FontFamily_fontProviderQuery;
			global::Xamarin.Essentials.Resource.Xml.xamarin_essentials_fileprovider_file_paths = global::MediaAndroidTest.Resource.Xml.xamarin_essentials_fileprovider_file_paths;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F010000
			public const int font = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int fontProviderAuthority = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int fontProviderCerts = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int fontProviderFetchStrategy = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int fontProviderFetchTimeout = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int fontProviderPackage = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int fontProviderQuery = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int fontStyle = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int fontWeight = 2130771976;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7F020000
			public const int abc_action_bar_embed_tabs = 2130837504;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F030000
			public const int notification_action_color_filter = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int notification_icon_bg_color = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int ripple_material_light = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int secondary_text_default_material_light = 2130903043;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F040000
			public const int compat_button_inset_horizontal_material = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int compat_button_inset_vertical_material = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int compat_button_padding_horizontal_material = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int compat_button_padding_vertical_material = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int compat_control_corner_material = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int notification_action_icon_size = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int notification_action_text_size = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int notification_big_circle_margin = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int notification_content_margin_start = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int notification_large_icon_height = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int notification_large_icon_width = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int notification_main_column_padding_top = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int notification_media_narrow_margin = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int notification_right_icon_size = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int notification_right_side_padding_top = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int notification_small_icon_background_padding = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int notification_small_icon_size_as_large = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int notification_subtext_size = 2130968593;
			
			// aapt resource value: 0x7F040012
			public const int notification_top_pad = 2130968594;
			
			// aapt resource value: 0x7F040013
			public const int notification_top_pad_large_text = 2130968595;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F050000
			public const int Icon = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int notification_action_background = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int notification_bg = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int notification_bg_low = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int notification_bg_low_normal = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int notification_bg_low_pressed = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int notification_bg_normal = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int notification_bg_normal_pressed = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int notification_icon_background = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int notification_template_icon_bg = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int notification_template_icon_low_bg = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int notification_tile_bg = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int notify_panel_notification_icon_bg = 2131034124;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F060005
			public const int actions = 2131099653;
			
			// aapt resource value: 0x7F060001
			public const int action_container = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int action_divider = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int action_image = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int action_text = 2131099652;
			
			// aapt resource value: 0x7F060006
			public const int async = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int blocking = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int button1 = 2131099656;
			
			// aapt resource value: 0x7F060009
			public const int button2 = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public const int button3 = 2131099658;
			
			// aapt resource value: 0x7F06000B
			public const int chronometer = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public const int forever = 2131099660;
			
			// aapt resource value: 0x7F06000D
			public const int icon = 2131099661;
			
			// aapt resource value: 0x7F06000E
			public const int icon_group = 2131099662;
			
			// aapt resource value: 0x7F06000F
			public const int imageView1 = 2131099663;
			
			// aapt resource value: 0x7F060010
			public const int info = 2131099664;
			
			// aapt resource value: 0x7F060011
			public const int italic = 2131099665;
			
			// aapt resource value: 0x7F060012
			public const int line1 = 2131099666;
			
			// aapt resource value: 0x7F060013
			public const int line3 = 2131099667;
			
			// aapt resource value: 0x7F060000
			public const int MyButton = 2131099648;
			
			// aapt resource value: 0x7F060014
			public const int normal = 2131099668;
			
			// aapt resource value: 0x7F060015
			public const int notification_background = 2131099669;
			
			// aapt resource value: 0x7F060016
			public const int notification_main_column = 2131099670;
			
			// aapt resource value: 0x7F060017
			public const int notification_main_column_container = 2131099671;
			
			// aapt resource value: 0x7F060018
			public const int right_icon = 2131099672;
			
			// aapt resource value: 0x7F060019
			public const int right_side = 2131099673;
			
			// aapt resource value: 0x7F06001A
			public const int switch_cancel = 2131099674;
			
			// aapt resource value: 0x7F06001B
			public const int switch_front = 2131099675;
			
			// aapt resource value: 0x7F06001C
			public const int switch_save_album = 2131099676;
			
			// aapt resource value: 0x7F06001D
			public const int switch_size = 2131099677;
			
			// aapt resource value: 0x7F06001E
			public const int tag_transition_group = 2131099678;
			
			// aapt resource value: 0x7F06001F
			public const int text = 2131099679;
			
			// aapt resource value: 0x7F060020
			public const int text2 = 2131099680;
			
			// aapt resource value: 0x7F060021
			public const int time = 2131099681;
			
			// aapt resource value: 0x7F060022
			public const int title = 2131099682;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F070000
			public const int status_bar_notification_info_maxnum = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F080000
			public const int Main = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int notification_action = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int notification_action_tombstone = 2131230722;
			
			// aapt resource value: 0x7F080003
			public const int notification_template_custom_big = 2131230723;
			
			// aapt resource value: 0x7F080004
			public const int notification_template_icon_group = 2131230724;
			
			// aapt resource value: 0x7F080005
			public const int notification_template_part_chronometer = 2131230725;
			
			// aapt resource value: 0x7F080006
			public const int notification_template_part_time = 2131230726;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F090000
			public const int ApplicationName = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int Hello = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int status_bar_notification_info_overflow = 2131296258;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0A0000
			public const int TextAppearance_Compat_Notification = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public const int TextAppearance_Compat_Notification_Info = 2131361793;
			
			// aapt resource value: 0x7F0A0002
			public const int TextAppearance_Compat_Notification_Line2 = 2131361794;
			
			// aapt resource value: 0x7F0A0003
			public const int TextAppearance_Compat_Notification_Time = 2131361795;
			
			// aapt resource value: 0x7F0A0004
			public const int TextAppearance_Compat_Notification_Title = 2131361796;
			
			// aapt resource value: 0x7F0A0005
			public const int Widget_Compat_NotificationActionContainer = 2131361797;
			
			// aapt resource value: 0x7F0A0006
			public const int Widget_Compat_NotificationActionText = 2131361798;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F010001,0x7F010002,0x7F010003,0x7F010004,0x7F010005,0x7F010006 }
			public static int[] FontFamily = new int[] {
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: { 0x1010532,0x1010533,0x101053F,0x7F010000,0x7F010007,0x7F010008 }
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					2130771968,
					2130771975,
					2130771976};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 3
			public const int FontFamilyFont_font = 3;
			
			// aapt resource value: 4
			public const int FontFamilyFont_fontStyle = 4;
			
			// aapt resource value: 5
			public const int FontFamilyFont_fontWeight = 5;
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderCerts = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderFetchStrategy = 2;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderFetchTimeout = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderPackage = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderQuery = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F0C0000
			public const int file_paths = 2131492864;
			
			// aapt resource value: 0x7F0C0001
			public const int xamarin_essentials_fileprovider_file_paths = 2131492865;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
